language: php

php:
  - 5.3
  - 5.4

before_script:
  - wget --quiet http://getcomposer.org/composer.phar
  - php composer.phar install --dev

after_script:
  - bin/php-cs-fixer fix ./ --dry-run --verbose

script: phpunit --coverage-text
